package com.privhealthai.assessment.dto;

import com.privhealthai.doctor.dto.DoctorDto;
import lombok.Builder;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Data
@Builder
public class AssessmentResponse {

    private UUID id;
    private String riskLevel;
    private BigDecimal riskScore;
    private String recommendation;
    private List<String> symptoms;
    private String additionalSymptoms;
    private int age;
    private String gender;
    private LocalDateTime createdAt;

    /** True when the AI analysis below was generated by the LLM (not just the rule engine). */
    private boolean aiPowered;
    private List<ConditionDto> possibleConditions;
    private List<MedicineDto> medicines;
    private String recommendedSpecialization;
    private String aiAdvice;
    private List<DoctorDto> recommendedDoctors;
}
